### ISSUE TITLE
Bug: One-hot function,  RuntimeError: Invalid index in scatter 

### ISSUE THREAD

**Issue by EmmaSRH** [chenwydj/ultra_high_resolution_segmentation#18]
Thanks for your work! But when I test my own data I met this problem.
Do you have any idea what caused it? 

Traceback (most recent call last):
  File "/home/srh/GLNet/train_deep_globe.py", line 106, in <module>
    loss = trainer.train(sample_batched, model, global_fixed)
  File "/home/srh/GLNet/helper.py", line 313, in train
    loss = self.criterion(outputs_global, labels_glb)
  File "/home/srh/GLNet/train_deep_globe.py", line 86, in <lambda>
    criterion = lambda x,y: criterion1(x, y)
  File "/home/srh/miniconda2/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/srh/GLNet/utils/loss.py", line 59, in forward
    if self.one_hot: target = one_hot(target, input.size(1))
  File "/home/srh/GLNet/utils/loss.py", line 34, in one_hot
    return mask.scatter_(1, index, ones)
RuntimeError: Invalid index in scatter at /opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:151

**Comment by chenwydj** [comment]
You could double check if `mask.size(1) <= index.max() + 1` in your case, which means the range of values in `index` (i.e. semantic class index) should not be larger than the #channels of the one_hot `mask`.

**Comment by EmmaSRH** [comment]
Thanks for your suggestion!

**Comment by sumitsumit8532-jpg** [comment]
@sumit_king_76
